version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=gym
      - POSTGRESQL_PASSWORD=gym
      - POSTGRESQL_DATABASE=gymApi
